### PR TITLE
Use configuration file instead of specifying packages on command-line

### PR DESCRIPTION
**Pull request by wkeese**
This will allow for easier skipping of certain packages without requiring lots of command-line typing, and improve the ability to handle non-dojo source code for processing.

### CODE REVIEW

**Comment by csnover** [comment]
Curiously, why run the parser against util to begin with? What is in there that needs API documentation?

**Comment by wkeese** [comment]
I wasn't trying to run against util, but it comes in when I do

```
$ ./parse.sh ../trunk
```

So.... I'm not sure what (if anything) is useful in util.   I suppose the build tool itself would be useful since people may want to write transforms.

**Comment by csnover** [comment]
The build tool has no API documentation in it at all because Rawld hates the dojodoc syntax or something like that. Anyway, I think we should probably just run explicitly against package directories for now, so this patch isn’t needed. Is that OK for you?

**Comment by wkeese** [comment]
Like this?

  $ ./parse.sh ../trunk/dojo ../trunk/dijit ../trunk/dojox

It's more typing, but OK.

**Comment by wkeese** [comment]
Turns out that util/doh also generates useful documentation, so we don't want to skip util/ altogether.

**Comment by csnover** [comment]
I’m actually going to make it so that the command line specifies a configuration file to load instead of a list of files, since the main config file in the repository shouldn’t just be all about Dojo and this will enable just the defined packages to be processed.

**Pull request closed without merging**
